repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: flake8
    - id: trailing-whitespace
    - id: name-tests-test
    - id: end-of-file-fixer
    - id: pretty-format-json

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      args: [--no-strict-optional, --ignore-missing-imports, --disalllow-untyped-defs, --disallow-incomplete-defs,
      --pretty]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.7.0
    hooks:
    - id: reorder-python-imports
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: pep257
